<?php
define('STRIPE_SECRET_KEY', getenv('STRIPE_SECRET_KEY') ?: '');       // sk_live_... / sk_test_...
define('STRIPE_WEBHOOK_SECRET', getenv('STRIPE_WEBHOOK_SECRET') ?: ''); // whsec_...
define('STRIPE_PRICE_PRO', getenv('STRIPE_PRICE_PRO') ?: '');          // price_... from Stripe dashboard
define('STRIPE_PRICE_BUSINESS', getenv('STRIPE_PRICE_BUSINESS') ?: '');